
server:
  port: 8093

spring:
  r2dbc:
    #    url: r2dbc:h2:mem:///userdb
    url: r2dbc:postgresql://localhost:5432/postgres
    username: admin
    password: 123456@

product:
  service:
    url: http://localhost:8091/product/
user:
  service:
    url: http://localhost:8092/user/
